title: "Exploring Complex Graph Representations of Highway Networks for Traffic Speed Forecasting"
author: "Ricky Miura, Gita Anand, Sheena Patel"
description: "HDSI Capstone 2024"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
paginate: 5

baseurl: '/dsc180b_B12_1_website.github.io' # TODO update this
url: 'https://sheenapatel262.github.io' # the base hostname & protocol for your site, e.g. http://example.com (don't change this)

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "README.md", title: "About Us"}
  - {title: Github, icon: github, url: "https://github.com/RickyMiura/Traffic-Speed-Forecasting/tree/main"}

<div style= "position: absolute; top: 10px; right: 10px;">
  <p>Ricky, Gita, Sheena</p>
</div>

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  # - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  # - {title: Github, icon: github, url: "https://github.com/RickyMiura/Traffic-Speed-Forecasting/tree/main"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - authors: "Ricky Miura, Gita Anand, Sheena Patel"
